### ISSUE TITLE
不要购买，非VIP可以登陆，VIP账号根本登陆不上，完全无法使用

### ISSUE THREAD

**Issue by Larrysong1111** [getfotiaoqiang/download#3]
不要购买，非VIP可以登陆，VIP账号根本登陆不上，完全无法使用

**Comment by Nanve** [comment]
> 不要购买，非VIP可以登陆，VIP账号根本登陆不上，完全无法使用

联系客服试试。我一直观望着没敢买

**Comment by Larrysong1111** [comment]
没什么用，客服联系不上

**Comment by Larrysong1111** [comment]
> > 不要购买，非VIP可以登陆，VIP账号根本登陆不上，完全无法使用
> 
> 联系客服试试。我一直观望着没敢买

没什么用，客服联系不上

**Comment by gearforcer** [comment]
感觉像骗子

**Comment by Fatezhang** [comment]
我也是这种情况，在 Windows 上登录还行，在 Mac 上总是掉线，然后自动连接游客账号
