### ISSUE TITLE
骗子啊。。免费测试的速度慢但可以正常使用，付费后就基本没法用了

### ISSUE THREAD

**Issue by Sanzo001** [getfotiaoqiang/download#5]
用了三天，第二天第三天还好，第一天气的我想投诉退钱，付费后280块/年的专业版后就基本没法用了，电脑没法用，手机浏览速度100多K，没办法看视频，切换各种专业版线路也不行，很多时候谷歌图标、youtube视频封面都显示不出来。
客服联系不上，官网下面的“联系我们”的按钮居然是假的。。。。
第二天可以正常使用了

**Comment by Yaziwel** [comment]
我也是

**Comment by lifankohome** [comment]
啊？骗人的啊？还好我没买
